/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pack_Laboratorium;

import Pack_Dosen.DialogTentang;
import Pack_Dosen.DialogDosen;
import Packages_Log_Database.Kelas_Database;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author NANO
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    Connection con;

    public Homepage() {
        initComponents();
        setTitle("HALAMAN UTAMA PENJADWALAN LAB TEKNIK INFORMATIKA SANATA DHARMA ");
        getTitle();
        ImageIcon icon = new ImageIcon("src/Gambar/Logo USD.png");
        setIconImage(icon.getImage());
    }
    public void tambahadmin(){
         try {
            ImageIcon icon = new ImageIcon("src/Gambar/Tambah.png");
            setIconImage(icon.getImage());
            String userDaftar = (String) JOptionPane.showInputDialog(rootPane, 
                    "Silahkan Input User Name", "Tambah Admin", 2, icon, null, null);
            String passDaftar = (String) JOptionPane.showInputDialog(rootPane, 
                    "Silahkan Input Password", "Tambah Admin", 2, icon, null, null);
            if (userDaftar.equals("") || (passDaftar.equals(""))) {
                JOptionPane.showMessageDialog(null, "User Name dan Password tidak boleh kosong", "Warning", 2);
            } else {
                Connection conn;
                Statement stat;
                ResultSet reset;
                String query;
               
                conn = new Kelas_Database().Koneksi();
                query = "INSERT into sam values ('" + userDaftar + "','" + passDaftar + "')";
                stat = conn.createStatement();
                reset = stat.executeQuery(query);
                JOptionPane.showMessageDialog(null, " Data Admin  Tersimpan");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Batal menambahkan admin", "Warning", 2);
        }
    }
    public void HapusAdmin(){
         Kelas_Database.Koneksi();
        try {
            String Admin = JOptionPane.showInputDialog("Masukan User name yang akan dihapus");
            if (Admin.equals("")) {
                JOptionPane.showMessageDialog(null, "User Name tidak boleh kosong", "Warning", 2);
            } else {
                int hapus = JOptionPane.showConfirmDialog(null, "Anda yakin akan menghapus Admin ?", "Konfirmasi",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (hapus == JOptionPane.NO_OPTION) {
                    JOptionPane.showMessageDialog(null, "batal menghapus");
                } else if (hapus == JOptionPane.YES_OPTION) {
                    Statement statement = con.createStatement();
                    String query = "delete from sam where usernam='" + Admin + "'";
                    statement.executeUpdate(query);
                    statement.close();
                    JOptionPane.showMessageDialog(null, " Berhasil Menghapus");
                }

            }
        } catch (Exception e) {

        }
    }
    Homepage(Object object, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        LihatPenggunaItem = new javax.swing.JMenuItem();
        ExitItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        InfoDosenItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        TambahAdminItem = new javax.swing.JMenuItem();
        HapusAdminItem = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/pa.jpg"))); // NOI18N

        jMenu3.setText("Penjadwalan");

        LihatPenggunaItem.setText("Lihat Pengguna Lab");
        LihatPenggunaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LihatPenggunaItemActionPerformed(evt);
            }
        });
        jMenu3.add(LihatPenggunaItem);

        ExitItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        ExitItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/ExitMenu.jpg"))); // NOI18N
        ExitItem.setText("Exit");
        ExitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitItemActionPerformed(evt);
            }
        });
        jMenu3.add(ExitItem);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Dosen");

        InfoDosenItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Information-icon.png"))); // NOI18N
        InfoDosenItem.setText("Info Dosen");
        InfoDosenItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoDosenItemActionPerformed(evt);
            }
        });
        jMenu4.add(InfoDosenItem);

        jMenuBar2.add(jMenu4);

        jMenu2.setText("Administrasi");

        TambahAdminItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        TambahAdminItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/tamMenu.jpg"))); // NOI18N
        TambahAdminItem.setText("Tambah Admin");
        TambahAdminItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahAdminItemActionPerformed(evt);
            }
        });
        jMenu2.add(TambahAdminItem);

        HapusAdminItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, 0));
        HapusAdminItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/hap.png"))); // NOI18N
        HapusAdminItem.setText("Hapus Admin");
        HapusAdminItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusAdminItemActionPerformed(evt);
            }
        });
        jMenu2.add(HapusAdminItem);

        jMenuBar2.add(jMenu2);

        jMenu5.setText("About");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Information-icon.png"))); // NOI18N
        jMenuItem1.setText("Tentang Kami");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuBar2.add(jMenu5);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TambahAdminItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahAdminItemActionPerformed
        tambahadmin();
    }//GEN-LAST:event_TambahAdminItemActionPerformed

    private void HapusAdminItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusAdminItemActionPerformed
        HapusAdmin();
    }//GEN-LAST:event_HapusAdminItemActionPerformed

    private void LihatPenggunaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LihatPenggunaItemActionPerformed
        dispose();
        DialogJadwal hari = new DialogJadwal(null, true);
        hari.setVisible(true);
    }//GEN-LAST:event_LihatPenggunaItemActionPerformed

    private void ExitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitItemActionPerformed
        int keluar = JOptionPane.showConfirmDialog(null, "Apakah anda akan keluar dari aplikasi ?", "Konfirmasi",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (keluar == JOptionPane.NO_OPTION) {
        } else if (keluar == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_ExitItemActionPerformed

    private void InfoDosenItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoDosenItemActionPerformed
        DialogDosen edit = new DialogDosen(this, true);
        edit.setVisible(true);
    }//GEN-LAST:event_InfoDosenItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        DialogTentang tentang = new DialogTentang(null, true);
        tentang.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ExitItem;
    private javax.swing.JMenuItem HapusAdminItem;
    private javax.swing.JMenuItem InfoDosenItem;
    private javax.swing.JMenuItem LihatPenggunaItem;
    private javax.swing.JMenuItem TambahAdminItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables

}
